### ISSUE TITLE
RaidToolkit fails to start with "An error occured"

### ISSUE THREAD

**Issue by curzona** [raid-toolkit/raid-toolkit-sdk#119]
Raid Toolkit fails to start with error message "An error occured" after detecting a new game version. After closing the window, the raid toolkit process is still running but doesn't work. I uninstalled and reinstalled RTK but I get the same error. There are no log files in `RaidToolkit\Logs` Any idea what I'm doing wrong and how to debug/fix the error?

![image](https://github.com/raid-toolkit/raid-toolkit-sdk/assets/1147498/ff814329-5a71-4bea-a0d8-c675912ca45c)

**Comment by Sachmet-Netjer** [comment]
There is an additional message concerning the game version.
![image](https://github.com/raid-toolkit/raid-toolkit-sdk/assets/93992828/6507c9cd-762e-4348-841c-a5fe06c4cf93)

**Comment by Maher-BAHI** [comment]
Hello, I'm having the same issue.
I would like to know if there is any update on the Raid Toolkit version, or the plan for patch to apply to support the new version of raid shadow legends Windows application. 
Best regards,

**Comment by Maher-BAHI** [comment]
I found the solution in this forum :
https://discord.com/channels/834891973776244807/1075422447756660756

**Comment by curzona** [comment]
Thanks. I had installed the latest released RTK version v2.3.9.30179. This doesn't work. However the pre-released version v2.4.18.62752 does work. It's unclear from the release notes what what changed in v2.4.x that causes it to work and why v2.3.x doesn't. 

Since the website and the github page both link to v2.3.9.30179, anyone installing RTK from these pages will encounter this error.

**Comment by cmarabate** [comment]
Yeah, I encountered the same exact problem. Only the pre-release version works but most people download the public version.

**Comment by dnchattan** [comment]
public version has been updated, so this should work everywhere now
