### ISSUE TITLE
Win 11 support

### ISSUE THREAD

**Issue by WOROTH** [raid-toolkit/raid-toolkit-sdk#42]
Got a feedback from a tester, who uses Win 11. He reports that RTK does not starts.
Do you have it in plans, or i should force him to use 10? )

**Comment by dnchattan** [comment]
Windows 11 should work fine. I'm developing using win11 😄 

They may need to install .net 5.0-windows here: https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-5.0.12-windows-x64-installer

**Comment by WOROTH** [comment]
You mean, the problem is on his side. 
Good :) Thanks!
