### ISSUE TITLE
Wrong number of total scrolls 

### ISSUE THREAD

**Issue by Sachmet-Netjer** [raid-toolkit/raid-toolkit-sdk#46]
Hi there,

ist seems to me as if TotalMasteryScrolls is calculated as double sum of UnasignedMasteryScrolls and AssignedMasteryScrolls.

AssignedMasteryScrolls_Bronze  :  100      100
AssignedMasteryScrolls_Silver  :  600      280
AssignedMasteryScrolls_Gold	   :  950      0      
UnassignedMasteryScrolls_Bronze:  0        0
UnassignedMasteryScrolls_Silver:  0        36
UnassignedMasteryScrolls_Gold  :  0        0
TotalMasteryScrolls_Bronze     :  200      200
TotalMasteryScrolls_Silver     :  1200     632
TotalMasteryScrolls_Gold       :  1900     0

Regards
Efro

**Comment by dnchattan** [comment]
yeah.... that's a bug :joy:

will have fix out shortly
